add custom assignee column
humanmade/Workflows pull request #154
Opened 2021-05-28 22:16 UTC by jazzsequence

Adds an Assignees column

- [x] Updated changelog
- [x] Updated version number in `package.json` and `plugin.php` file with appropriate MAJOR.MINOR.PATCH change

2021-05-31 16:00 UTC, jazzsequence commented
**Note:** Linter is failing due to an unrelated apparent issue with `/admin/package.json` -- documented [here](https://github.com/humanmade/Workflows/issues/155)

2021-06-01 13:40 UTC, roborourke requested changes
Couple of improvements to make on the column code, and a suggested change to only add the column for post types that support editorial comments. I know it wouldn't have been strictly clear that those 2 things are functionally bound together right now because of the post lists filter. Might be good to fix that too as part of this PR.

2021-06-01 13:40 UTC, roborourke commented on admin/admin.php
> +	if ( $column === 'assignees' ) {
Return early here instead to avoid the deep nesting.

2021-06-01 13:40 UTC, roborourke commented on admin/admin.php
> +				'<a href="%1$s">%2$s%3$s</a> ',
Seems odd to have the separator inside the link here. I think it would be more straight forward to `array_map()` the users into links, and then use `implode( ', ', $users )` so you don't need to worry about the separator logic.

2021-06-01 17:02 UTC, jazzsequence commented on admin/admin.php
> +	$post_types = get_post_types( ['public' => true], 'names' );
Oooh, that makes sense. I was looking all over to try to figure out where to get the supported post types. This explains a lot. 😅

2021-06-01 17:05 UTC, jazzsequence commented on admin/admin.php
> +				'<a href="%1$s">%2$s%3$s</a> ',
Good call. Not sure where my brain was at when I put the comma inside the link. 🤔

2021-06-02 09:44 UTC, roborourke approved these changes
Tidy, thanks @jazzsequence 👍

2021-06-02 09:44 UTC, merged