Exclude editorial comments in post comment count.
humanmade/Workflows pull request #195
Opened 2022-08-08 14:30 UTC by robindevitt

Related Issue : https://github.com/humanmade/Workflows/issues/194

Currently the comment count is displayed as a combined total of comments and editorial comments. This PR excludes "workflow" comments from the post comment count, giving a true number of comments per post.

- [ ] Updated changelog
- [ ] Updated version number in `package.json` and `plugin.php` file with appropriate MAJOR.MINOR.PATCH change

2022-08-08 18:03 UTC, roborourke reviewed
How does WP calculate comment counts normally? Does `get_comments` or `WP_Comment_Query` have anything like the option to just return a count or IDs instead of entire records? Does this work if comments are paginated?

2022-08-10 07:04 UTC, robindevitt commented
>How does WP calculate comment counts normally? Does `get_comments` or `WP_Comment_Query` have anything like the option to just return a count or IDs instead of entire records? Does this work if comments are paginated?

The comment count in the column uses the function `get_comments_number` which retrieves the total number of comments a post has. This includes the workflow comments. The filter allows us to run `get_comments` and exclude workflow comments from the count and return the new count.

2022-08-10 12:58 UTC, roborourke commented
> The filter allows us to run get_comments without pagination and exclude workflow comments from the count and return the new comment count.

I once took down a site by not paginating comments, plus we enforce it in Altis so I'd prefer if we double checked this. I'm concerned how this would perform with 100s or 1000s of comments.

2022-08-10 13:10 UTC, roborourke requested changes

2022-08-10 13:10 UTC, roborourke commented on lib/events/new-editorial-comment.php
> +	$comments = get_comments( $args );
Have a look through the arguments you can pass to `WP_Comment_Query` here (`get_comments()` is a wrapper around that), specifically the `count` parameter https://developer.wordpress.org/reference/classes/wp_comment_query/__construct/

2022-08-10 13:10 UTC, roborourke commented on lib/events/new-editorial-comment.php
> +		'type__not_in' => ['workflow'],
```suggestion
		'type__not_in' => [ 'workflow' ],
```

2022-08-10 15:18 UTC, mikelittle reviewed
Same comment as Rob really.

2022-08-11 07:25 UTC, robindevitt commented on lib/events/new-editorial-comment.php
> +	$comments = get_comments( $args );
Gotcha, I have made use of the `count` parameter. Using the `count` parameter it appears to also bypass pagination.

2022-08-11 09:11 UTC, roborourke approved these changes
One code style change to add in.

2022-08-11 09:11 UTC, roborourke commented on lib/events/new-editorial-comment.php
> + * @param int $post_id
Missing parameter descriptions here
```suggestion
 * @param int $count The current number of comments found.
 * @param int $post_id The post ID to return the number of comments for.
```

2022-08-11 11:24 UTC, merged